package topen.deathmessage.configuredeathmessage;

public class Resources {
    public static String getEN(){
        return """
                {"death.fell.accident.ladder": "(.*) fell off a ladder",
                  "death.fell.accident.vines": "(.*) fell off some vines",
                  "death.fell.accident.weeping_vines": "(.*) fell off some weeping vines",
                  "death.fell.accident.twisting_vines": "(.*) fell off some twisting vines",
                  "death.fell.accident.scaffolding": "(.*) fell off scaffolding",
                  "death.fell.accident.other_climbable": "(.*) fell while climbing",
                  "death.fell.accident.generic": "(.*) fell from a high place",
                  "death.fell.killer": "(.*) was doomed to fall",
                  "death.fell.assist": "(.*) was doomed to fall by (.*)",
                  "death.fell.assist.item": "(.*) was doomed to fall by (.*) using (.*)",
                  "death.fell.finish": "(.*) fell too far and was finished by (.*)",
                  "death.fell.finish.item": "(.*) fell too far and was finished by (.*) using (.*)",
                  "death.attack.lightningBolt": "(.*) was struck by lightning",
                  "death.attack.lightningBolt.player": "(.*) was struck by lightning whilst fighting (.*)",
                  "death.attack.inFire": "(.*) went up in flames",
                  "death.attack.inFire.player": "(.*) walked into fire whilst fighting (.*)",
                  "death.attack.onFire": "(.*) burned to death",
                  "death.attack.onFire.item": "(.*) was burnt to a crisp whilst fighting (.*) wielding (.*)",
                  "death.attack.onFire.player": "(.*) was burnt to a crisp whilst fighting (.*)",
                  "death.attack.lava": "(.*) tried to swim in lava",
                  "death.attack.lava.player": "(.*) tried to swim in lava to escape (.*)",
                  "death.attack.hotFloor": "(.*) discovered the floor was lava",
                  "death.attack.hotFloor.player": "(.*) walked into danger zone due to (.*)",
                  "death.attack.inWall": "(.*) suffocated in a wall",
                  "death.attack.inWall.player": "(.*) suffocated in a wall whilst fighting (.*)",
                  "death.attack.cramming": "(.*) was squished too much",
                  "death.attack.cramming.player": "(.*) was squashed by (.*)",
                  "death.attack.drown": "(.*) drowned",
                  "death.attack.drown.player": "(.*) drowned whilst trying to escape (.*)",
                  "death.attack.dryout": "(.*) died from dehydration",
                  "death.attack.dryout.player": "(.*) died from dehydration whilst trying to escape (.*)",
                  "death.attack.starve": "(.*) starved to death",
                  "death.attack.starve.player": "(.*) starved to death whilst fighting (.*)",
                  "death.attack.cactus": "(.*) was pricked to death",
                  "death.attack.cactus.player": "(.*) walked into a cactus whilst trying to escape (.*)",
                  "death.attack.generic": "(.*) died",
                  "death.attack.generic.player": "(.*) died because of (.*)",
                  "death.attack.explosion": "(.*) blew up",
                  "death.attack.explosion.player": "(.*) was blown up by (.*)",
                  "death.attack.explosion.player.item": "(.*) was blown up by (.*) using (.*)",
                  "death.attack.magic": "(.*) was killed by magic",
                  "death.attack.magic.player": "(.*) was killed by magic whilst trying to escape (.*)",
                  "death.attack.even_more_magic": "(.*) was killed by even more magic",
                  "death.attack.message_too_long": "Actually, message was too long to deliver fully. Sorry! Here's stripped version: (.*)",
                  "death.attack.wither": "(.*) withered away",
                  "death.attack.wither.player": "(.*) withered away whilst fighting (.*)",
                  "death.attack.witherSkull": "(.*) was shot by a skull from (.*)",
                  "death.attack.witherSkull.item": "(.*) was shot by a skull from (.*) using (.*)",
                  "death.attack.anvil": "(.*) was squashed by a falling anvil",
                  "death.attack.anvil.player": "(.*) was squashed by a falling anvil whilst fighting (.*)",
                  "death.attack.fallingBlock": "(.*) was squashed by a falling block",
                  "death.attack.fallingBlock.player": "(.*) was squashed by a falling block whilst fighting (.*)",
                  "death.attack.stalagmite": "(.*) was impaled on a stalagmite",
                  "death.attack.stalagmite.player": "(.*) was impaled on a stalagmite whilst fighting (.*)",
                  "death.attack.fallingStalactite": "(.*) was skewered by a falling stalactite",
                  "death.attack.fallingStalactite.player": "(.*) was skewered by a falling stalactite whilst fighting (.*)",
                  "death.attack.sonic_boom": "(.*) was obliterated by a sonically-charged shriek",
                  "death.attack.sonic_boom.item": "(.*) was obliterated by a sonically-charged shriek whilst trying to escape (.*) wielding (.*)",
                  "death.attack.sonic_boom.player": "(.*) was obliterated by a sonically-charged shriek whilst trying to escape (.*)",
                  "death.attack.mob": "(.*) was slain by (.*)",
                  "death.attack.mob.item": "(.*) was slain by (.*) using (.*)",
                  "death.attack.player": "(.*) was slain by (.*)",
                  "death.attack.player.item": "(.*) was slain by (.*) using (.*)",
                  "death.attack.arrow": "(.*) was shot by (.*)",
                  "death.attack.arrow.item": "(.*) was shot by (.*) using (.*)",
                  "death.attack.fireball": "(.*) was fireballed by (.*)",
                  "death.attack.fireball.item": "(.*) was fireballed by (.*) using (.*)",
                  "death.attack.thrown": "(.*) was pummeled by (.*)",
                  "death.attack.thrown.item": "(.*) was pummeled by (.*) using (.*)",
                  "death.attack.indirectMagic": "(.*) was killed by (.*) using magic",
                  "death.attack.indirectMagic.item": "(.*) was killed by (.*) using (.*)",
                  "death.attack.thorns": "(.*) was killed trying to hurt (.*)",
                  "death.attack.thorns.item": "(.*) was killed by (.*) trying to hurt (.*)",
                  "death.attack.trident": "(.*) was impaled by (.*)",
                  "death.attack.trident.item": "(.*) was impaled by (.*) with (.*)",
                  "death.attack.fall": "(.*) hit the ground too hard",
                  "death.attack.fall.player": "(.*) hit the ground too hard whilst trying to escape (.*)",
                  "death.attack.outOfWorld": "(.*) fell out of the world",
                  "death.attack.outOfWorld.player": "(.*) didn't want to live in the same world as (.*)",
                  "death.attack.dragonBreath": "(.*) was roasted in dragon breath",
                  "death.attack.dragonBreath.player": "(.*) was roasted in dragon breath by (.*)",
                  "death.attack.flyIntoWall": "(.*) experienced kinetic energy",
                  "death.attack.flyIntoWall.player": "(.*) experienced kinetic energy whilst trying to escape (.*)",
                  "death.attack.fireworks": "(.*) went off with a bang",
                  "death.attack.fireworks.player": "(.*) went off with a bang whilst fighting (.*)",
                  "death.attack.fireworks.item": "(.*) went off with a bang due to a firework fired from (.*) by (.*)",
                  "death.attack.badRespawnPoint.message": "(.*) was killed by (.*)",
                  "death.attack.badRespawnPoint.link": "Intentional Game Design",
                  "death.attack.sweetBerryBush": "(.*) was poked to death by a sweet berry bush",
                  "death.attack.sweetBerryBush.player": "(.*) was poked to death by a sweet berry bush whilst trying to escape (.*)",
                  "death.attack.sting": "(.*) was stung to death",
                  "death.attack.sting.item": "(.*) was stung to death by (.*) using (.*)",
                  "death.attack.sting.player": "(.*) was stung to death by (.*)",
                  "death.attack.freeze": "(.*) froze to death",
                  "death.attack.freeze.player": "(.*) was frozen to death by (.*)"
                }
                """;
    }

    public static String getEN_O(){
        return """
                {
                "death.fell.accident.ladder": "1",
                "death.fell.accident.vines": "1",
                "death.fell.accident.weeping_vines": "1",
                "death.fell.accident.twisting_vines": "1",
                "death.fell.accident.scaffolding": "1",
                "death.fell.accident.other_climbable": "1",
                "death.fell.accident.generic": "1",
                "death.fell.killer": "1",
                "death.fell.assist": "1 2",
                "death.fell.assist.item": "1 2 3",
                "death.fell.finish": "1 2",
                "death.fell.finish.item": "1 2 3",
                "death.attack.lightningBolt": "1",
                "death.attack.lightningBolt.player": "1 2",
                "death.attack.inFire": "1",
                "death.attack.inFire.player": "1 2",
                "death.attack.onFire": "1",
                "death.attack.onFire.item": "1 2 3",
                "death.attack.onFire.player": "1 2",
                "death.attack.lava": "1",
                "death.attack.lava.player":  "1 2",
                "death.attack.hotFloor": "1",
                "death.attack.hotFloor.player":  "1 2",
                "death.attack.inWall": "1",
                "death.attack.inWall.player":  "1 2",
                "death.attack.cramming": "1",
                "death.attack.cramming.player":  "1 2",
                "death.attack.drown": "1",
                "death.attack.drown.player":  "1 2",
                "death.attack.dryout": "1",
                "death.attack.dryout.player":  "1 2",
                "death.attack.starve": "1",
                "death.attack.starve.player": "1 2",
                "death.attack.cactus": "1",
                "death.attack.cactus.player": "1 2",
                "death.attack.generic": "1",
                "death.attack.generic.player": "1 2",
                "death.attack.explosion": "1",
                "death.attack.explosion.player": "1 2",
                "death.attack.explosion.player.item": "1 2 3",
                "death.attack.magic": "1",
                "death.attack.magic.player": "1 2",
                "death.attack.even_more_magic": "1",
                "death.attack.message_too_long": "1",
                "death.attack.wither": "1",
                "death.attack.wither.player":  "1 2",
                "death.attack.witherSkull": "1",
                "death.attack.witherSkull.item": "1 2 3",
                "death.attack.anvil": "1",
                "death.attack.anvil.player":  "1 2",
                "death.attack.fallingBlock": "1",
                "death.attack.fallingBlock.player": "1 2",
                "death.attack.stalagmite": "1",
                "death.attack.stalagmite.player":  "1 2",
                "death.attack.fallingStalactite": "1",
                "death.attack.fallingStalactite.player": "1 2",
                "death.attack.sonic_boom": "1",
                "death.attack.sonic_boom.item": "1 2 3",
                "death.attack.sonic_boom.player":  "1 2",
                "death.attack.mob": "1 2",
                "death.attack.mob.item": "1 2 3",
                "death.attack.player": "1 2",
                "death.attack.player.item": "1 2 3",
                "death.attack.arrow": "1 2",
                "death.attack.arrow.item": "1 2 3",
                "death.attack.fireball": "1 2",
                "death.attack.fireball.item": "1 2 3",
                "death.attack.thrown": "1 2",
                "death.attack.thrown.item": "1 2 3",
                "death.attack.indirectMagic": "1 2",
                "death.attack.indirectMagic.item":  "1 2 3",
                "death.attack.thorns": "1 2",
                "death.attack.thorns.item": "1 3 2",
                "death.attack.trident": "1 2",
                "death.attack.trident.item": "1 2 3",
                "death.attack.fall": "1",
                "death.attack.fall.player": "1 2",
                "death.attack.outOfWorld": "1",
                "death.attack.outOfWorld.player": "1 2",
                "death.attack.dragonBreath": "1",
                "death.attack.dragonBreath.player": "1 2",
                "death.attack.flyIntoWall": "1",
                "death.attack.flyIntoWall.player": "1 2",
                "death.attack.fireworks": "1",
                "death.attack.fireworks.player":  "1 2",
                "death.attack.fireworks.item": "1 2",
                "death.attack.badRespawnPoint.message":  "1 3 2",
                "death.attack.badRespawnPoint.link": "",
                "death.attack.sweetBerryBush": "1",
                "death.attack.sweetBerryBush.player": "1 2",
                "death.attack.sting": "1",
                "death.attack.sting.item":  "1 2 3",
                "death.attack.sting.player": "1 2",
                "death.attack.freeze": "1",
                "death.attack.freeze.player": "1 2"
                }
                """;
    }

    public static String getKO_KR(){
        return """
                {
                  "death.attack.anvil": "%1$s이(가) 떨어지는 모루에 짓눌렸습니다",
                  "death.attack.anvil.player": "%1$s이(가) %2$s과(와) 싸우다가 떨어지는 모루에 짓눌렸습니다",
                  "death.attack.arrow": "%1$s이(가) %2$s에게 저격당했습니다",
                  "death.attack.arrow.item": "%1$s이(가) %2$s에게 %3$s(으)로 저격당했습니다",
                  "death.attack.badRespawnPoint.link": "의도적 게임 설계",
                  "death.attack.badRespawnPoint.message": "%1$s이(가) %2$s 때문에 죽었습니다",
                  "death.attack.cactus": "%1$s이(가) 찔려 사망했습니다",
                  "death.attack.cactus.player": "%1$s이(가) %2$s에게서 도망치려다 선인장에 찔렸습니다",
                  "death.attack.cramming": "%1$s이(가) 으깨져버렸습니다",
                  "death.attack.cramming.player": "%1$s이(가) %2$s에게 짓눌렸습니다",
                  "death.attack.dragonBreath": "%1$s이(가) 드래곤의 숨결에 구워졌습니다",
                  "death.attack.dragonBreath.player": "%1$s이(가) %2$s 때문에 드래곤의 숨결에 구워졌습니다",
                  "death.attack.drown": "%1$s이(가) 익사했습니다",
                  "death.attack.drown.player": "%1$s이(가) %2$s에게서 도망치려다 익사했습니다",
                  "death.attack.dryout": "%1$s이(가) 탈수로 죽었습니다",
                  "death.attack.dryout.player": "%1$s이(가) %2$s에게서 도망치려다 탈수로 죽었습니다",
                  "death.attack.even_more_magic": "%1$s이(가) 더욱 심오한 마법으로 살해당했습니다",
                  "death.attack.explosion": "%1$s이(가) 폭파당했습니다",
                  "death.attack.explosion.player": "%1$s이(가) %2$s 때문에 폭사했습니다",
                  "death.attack.explosion.player.item": "%1$s이(가) %3$s을(를) 사용한 %2$s 때문에 폭사했습니다",
                  "death.attack.fall": "%1$s이(가) 땅바닥으로 곤두박질쳤습니다",
                  "death.attack.fall.player": "%1$s이(가) %2$s에게서 도망치려다 땅바닥으로 곤두박질쳤습니다",
                  "death.attack.fallingBlock": "%1$s이(가) 떨어지는 블록에 짓눌렸습니다",
                  "death.attack.fallingBlock.player": "%1$s이(가) %2$s과(와) 싸우다가 떨어지는 블록에 짓눌렸습니다",
                  "death.attack.fallingStalactite": "%1$s이(가) 떨어지는 종유석에 찔렸습니다",
                  "death.attack.fallingStalactite.player": "%1$s이(가) %2$s과(와) 싸우다가 떨어지는 종유석에 찔렸습니다",
                  "death.attack.fireball": "%1$s이(가) %2$s이(가) 던진 화염구에 맞았습니다",
                  "death.attack.fireball.item": "%1$s이(가) %3$s을(를) 사용한 %2$s이(가) 던진 화염구에 맞았습니다",
                  "death.attack.fireworks": "%1$s이(가) 굉음과 함께 폭사했습니다",
                  "death.attack.fireworks.item": "%1$s이(가) %2$s이(가) %3$s(으)로 쏜 폭죽 때문에 굉음과 함께 폭사했습니다",
                  "death.attack.fireworks.player": "%1$s이(가) %2$s과(와) 싸우다가 굉음과 함께 폭사했습니다",
                  "death.attack.flyIntoWall": "%1$s이(가) 운동 에너지를 온몸으로 경험했습니다",
                  "death.attack.flyIntoWall.player": "%1$s이(가) %2$s에게서 도망치려다 운동 에너지를 온몸으로 느꼈습니다",
                  "death.attack.freeze": "%1$s이(가) 얼어 죽었습니다",
                  "death.attack.freeze.player": "%1$s이(가) %2$s 때문에 얼어 죽었습니다",
                  "death.attack.generic": "%1$s이(가) 사망했습니다",
                  "death.attack.generic.player": "%1$s이(가) %2$s 때문에 죽었습니다",
                  "death.attack.hotFloor": "%1$s이(가) 바닥이 용암인 것을 알아챘습니다",
                  "death.attack.hotFloor.player": "%1$s이(가) %2$s 때문에 위험 지대에 빠졌습니다",
                  "death.attack.inFire": "%1$s이(가) 화염에 휩싸였습니다",
                  "death.attack.inFire.player": "%1$s이(가) %2$s과(와) 싸우다가 불에 빠졌습니다",
                  "death.attack.inWall": "%1$s이(가) 벽 속에서 질식했습니다",
                  "death.attack.inWall.player": "%1$s이(가) %2$s과(와) 싸우다가 벽 속에서 질식했습니다",
                  "death.attack.indirectMagic": "%1$s이(가) %2$s에게 마법으로 살해당했습니다",
                  "death.attack.indirectMagic.item": "%1$s이(가) %2$s에게 %3$s(으)로 살해당했습니다",
                  "death.attack.lava": "%1$s이(가) 용암에 빠졌습니다",
                  "death.attack.lava.player": "%1$s이(가) %2$s에게서 도망치려다 용암에 빠졌습니다",
                  "death.attack.lightningBolt": "%1$s이(가) 벼락을 맞았습니다",
                  "death.attack.lightningBolt.player": "%1$s이(가) %2$s과(와) 싸우다가 벼락을 맞았습니다",
                  "death.attack.magic": "%1$s이(가) 마법으로 살해당했습니다",
                  "death.attack.magic.player": "%1$s이(가) %2$s에게서 도망치려다 마법으로 살해당했습니다",
                  "death.attack.message_too_long": "완전히 전달하기에는 메시지가 너무 길었습니다. 죄송합니다! 잘라낸 메시지입니다: %s",
                  "death.attack.mob": "%1$s이(가) %2$s에게 살해당했습니다",
                  "death.attack.mob.item": "%1$s이(가) %2$s에게 %3$s(으)로 살해당했습니다",
                  "death.attack.onFire": "%1$s이(가) 불에 타 사망했습니다",
                  "death.attack.onFire.item": "%1$s이(가) %3$s을(를) 든 %2$s과(와) 싸우다가 바삭하게 구워졌습니다",
                  "death.attack.onFire.player": "%1$s이(가) %2$s과(와) 싸우다가 바삭하게 구워졌습니다",
                  "death.attack.outOfWorld": "%1$s이(가) 세계 밖으로 떨어졌습니다",
                  "death.attack.outOfWorld.player": "%1$s은(는) %2$s과(와)는 도저히 한 하늘을 같이 이고 살 수 없었습니다",
                  "death.attack.player": "%1$s이(가) %2$s에게 살해당했습니다",
                  "death.attack.player.item": "%1$s이(가) %2$s에게 %3$s(으)로 살해당했습니다",
                  "death.attack.sonic_boom": "%1$s은(는) 강한 음파의 비명에 말살됐습니다",
                  "death.attack.sonic_boom.item": "%1$s이(가) %3$s을(를) 든 %2$s에게서 도망치려다 강한 음파의 비명에 말살됐습니다",
                  "death.attack.sonic_boom.player": "%1$s이(가) %2$s에게서 도망치려다 강한 음파의 비명에 말살됐습니다",
                  "death.attack.stalagmite": "%1$s이(가) 석순에 찔렸습니다",
                  "death.attack.stalagmite.player": "%1$s이(가) %2$s과(와) 싸우다가 석순에 찔렸습니다",
                  "death.attack.starve": "%1$s이(가) 아사했습니다",
                  "death.attack.starve.player": "%1$s이(가) %2$s과(와) 싸우다가 아사했습니다",
                  "death.attack.sting": "%1$s이(가) 쏘여 사망했습니다",
                  "death.attack.sting.item": "%1$s이(가) %3$s을(를) 사용한 %2$s에게 쏘여 사망했습니다",
                  "death.attack.sting.player": "%1$s이(가) %2$s에게 쏘여 사망했습니다",
                  "death.attack.sweetBerryBush": "%1$s이(가) 달콤한 열매 덤불에 찔려 죽었습니다",
                  "death.attack.sweetBerryBush.player": "%1$s이(가) %2$s에게서 도망치려다 달콤한 열매 덤불에 찔려 죽었습니다",
                  "death.attack.thorns": "%1$s이(가) %2$s을(를) 해치려다 살해당했습니다",
                  "death.attack.thorns.item": "%1$s이(가) %2$s을(를) 해치려다 %3$s(으)로 살해당했습니다",
                  "death.attack.thrown": "%1$s이(가) %2$s에게 구타당했습니다",
                  "death.attack.thrown.item": "%1$s이(가) %2$s에게 %3$s(으)로 구타당했습니다",
                  "death.attack.trident": "%1$s이(가) %2$s에게 찔렸습니다",
                  "death.attack.trident.item": "%1$s이(가) %3$s을(를) 사용한 %2$s에게 찔렸습니다",
                  "death.attack.wither": "%1$s이(가) 사그라졌습니다",
                  "death.attack.wither.player": "%1$s이(가) %2$s과(와) 싸우다가 사그라졌습니다",
                  "death.attack.witherSkull": "%1$s이(가) %2$s에게 해골로 저격당했습니다",
                  "death.attack.witherSkull.item": "%1$s이(가) %3$s을(를) 사용한 %2$s에게 해골로 저격당했습니다",
                  "death.fell.accident.generic": "%1$s이(가) 높은 곳에서 떨어졌습니다",
                  "death.fell.accident.ladder": "%1$s이(가) 사다리에서 떨어졌습니다",
                  "death.fell.accident.other_climbable": "%1$s이(가) 무언가를 타고 오르던 중 떨어졌습니다",
                  "death.fell.accident.scaffolding": "%1$s이(가) 비계에서 떨어졌습니다",
                  "death.fell.accident.twisting_vines": "%1$s이(가) 휘어진 덩굴에서 떨어졌습니다",
                  "death.fell.accident.vines": "%1$s이(가) 덩굴에서 떨어졌습니다",
                  "death.fell.accident.weeping_vines": "%1$s이(가) 늘어진 덩굴에서 떨어졌습니다",
                  "death.fell.assist": "%1$s은(는) %2$s 때문에 추락을 피하지 못 했습니다",
                  "death.fell.assist.item": "%1$s은(는) %3$s을(를) 사용한 %2$s 때문에 추락을 피하지 못 했습니다",
                  "death.fell.finish": "%1$s이(가) 너무 높은 곳에서 떨어진 후, %2$s에게 최후를 맞이했습니다",
                  "death.fell.finish.item": "%1$s이(가) 너무 높은 곳에서 떨어진 후, %3$s을(를) 사용한 %2$s에게 최후를 맞이했습니다",
                  "death.fell.killer": "%1$s은(는) 추락을 피하지 못 했습니다"
                }
                """;
    }
    
    public static String getEN_OR(){
        return """
                {
                "death.fell.accident.ladder": "{1} fell off a ladder",
                  "death.fell.accident.vines": "{1} fell off some vines",
                  "death.fell.accident.weeping_vines": "{1} fell off some weeping vines",
                  "death.fell.accident.twisting_vines": "{1} fell off some twisting vines",
                  "death.fell.accident.scaffolding": "{1} fell off scaffolding",
                  "death.fell.accident.other_climbable": "{1} fell while climbing",
                  "death.fell.accident.generic": "{1} fell from a high place",
                  "death.fell.killer": "{1} was doomed to fall",
                  "death.fell.assist": "{1} was doomed to fall by {2}",
                  "death.fell.assist.item": "{1} was doomed to fall by {2} using {3}",
                  "death.fell.finish": "{1} fell too far and was finished by {2}",
                  "death.fell.finish.item": "{1} fell too far and was finished by {2} using {3}",
                  "death.attack.lightningBolt": "{1} was struck by lightning",
                  "death.attack.lightningBolt.player": "{1} was struck by lightning whilst fighting {2}",
                  "death.attack.inFire": "{1} went up in flames",
                  "death.attack.inFire.player": "{1} walked into fire whilst fighting {2}",
                  "death.attack.onFire": "{1} burned to death",
                  "death.attack.onFire.item": "{1} was burnt to a crisp whilst fighting {2} wielding {3}",
                  "death.attack.onFire.player": "{1} was burnt to a crisp whilst fighting {2}",
                  "death.attack.lava": "{1} tried to swim in lava",
                  "death.attack.lava.player": "{1} tried to swim in lava to escape {2}",
                  "death.attack.hotFloor": "{1} discovered the floor was lava",
                  "death.attack.hotFloor.player": "{1} walked into danger zone due to {2}",
                  "death.attack.inWall": "{1} suffocated in a wall",
                  "death.attack.inWall.player": "{1} suffocated in a wall whilst fighting {2}",
                  "death.attack.cramming": "{1} was squished too much",
                  "death.attack.cramming.player": "{1} was squashed by {2}",
                  "death.attack.drown": "{1} drowned",
                  "death.attack.drown.player": "{1} drowned whilst trying to escape {2}",
                  "death.attack.dryout": "{1} died from dehydration",
                  "death.attack.dryout.player": "{1} died from dehydration whilst trying to escape {2}",
                  "death.attack.starve": "{1} starved to death",
                  "death.attack.starve.player": "{1} starved to death whilst fighting {2}",
                  "death.attack.cactus": "{1} was pricked to death",
                  "death.attack.cactus.player": "{1} walked into a cactus whilst trying to escape {2}",
                  "death.attack.generic": "{1} died",
                  "death.attack.generic.player": "{1} died because of {2}",
                  "death.attack.explosion": "{1} blew up",
                  "death.attack.explosion.player": "{1} was blown up by {2}",
                  "death.attack.explosion.player.item": "{1} was blown up by {2} using {3}",
                  "death.attack.magic": "{1} was killed by magic",
                  "death.attack.magic.player": "{1} was killed by magic whilst trying to escape {2}",
                  "death.attack.even_more_magic": "{1} was killed by even more magic",
                  "death.attack.message_too_long": "Actually, message was too long to deliver fully. Sorry! Here's stripped version: {1}",
                  "death.attack.wither": "{1} withered away",
                  "death.attack.wither.player": "{1} withered away whilst fighting {2}",
                  "death.attack.witherSkull": "{1} was shot by a skull from {2}",
                  "death.attack.witherSkull.item": "{1} was shot by a skull from {2} using {3}",
                  "death.attack.anvil": "{1} was squashed by a falling anvil",
                  "death.attack.anvil.player": "{1} was squashed by a falling anvil whilst fighting {2}",
                  "death.attack.fallingBlock": "{1} was squashed by a falling block",
                  "death.attack.fallingBlock.player": "{1} was squashed by a falling block whilst fighting {2}",
                  "death.attack.stalagmite": "{1} was impaled on a stalagmite",
                  "death.attack.stalagmite.player": "{1} was impaled on a stalagmite whilst fighting {2}",
                  "death.attack.fallingStalactite": "{1} was skewered by a falling stalactite",
                  "death.attack.fallingStalactite.player": "{1} was skewered by a falling stalactite whilst fighting {2}",
                  "death.attack.sonic_boom": "{1} was obliterated by a sonically-charged shriek",
                  "death.attack.sonic_boom.item": "{1} was obliterated by a sonically-charged shriek whilst trying to escape {2} wielding {3}",
                  "death.attack.sonic_boom.player": "{1} was obliterated by a sonically-charged shriek whilst trying to escape {2}",
                  "death.attack.mob": "{1} was slain by {2}",
                  "death.attack.mob.item": "{1} was slain by {2} using {3}",
                  "death.attack.player": "{1} was slain by {2}",
                  "death.attack.player.item": "{1} was slain by {2} using {3}",
                  "death.attack.arrow": "{1} was shot by {2}",
                  "death.attack.arrow.item": "{1} was shot by {2} using {3}",
                  "death.attack.fireball": "{1} was fireballed by {2}",
                  "death.attack.fireball.item": "{1} was fireballed by {2} using {3}",
                  "death.attack.thrown": "{1} was pummeled by {2}",
                  "death.attack.thrown.item": "{1} was pummeled by {2} using {3}",
                  "death.attack.indirectMagic": "{1} was killed by {2} using magic",
                  "death.attack.indirectMagic.item": "{1} was killed by {2} using {3}",
                  "death.attack.thorns": "{1} was killed trying to hurt {2}",
                  "death.attack.thorns.item": "{1} was killed by {3} trying to hurt {2}",
                  "death.attack.trident": "{1} was impaled by {2}",
                  "death.attack.trident.item": "{1} was impaled by {2} with {3}",
                  "death.attack.fall": "{1} hit the ground too hard",
                  "death.attack.fall.player": "{1} hit the ground too hard whilst trying to escape {2}",
                  "death.attack.outOfWorld": "{1} fell out of the world",
                  "death.attack.outOfWorld.player": "{1} didn't want to live in the same world as {2}",
                  "death.attack.dragonBreath": "{1} was roasted in dragon breath",
                  "death.attack.dragonBreath.player": "{1} was roasted in dragon breath by {2}",
                  "death.attack.flyIntoWall": "{1} experienced kinetic energy",
                  "death.attack.flyIntoWall.player": "{1} experienced kinetic energy whilst trying to escape {2}",
                  "death.attack.fireworks": "{1} went off with a bang",
                  "death.attack.fireworks.player": "{1} went off with a bang whilst fighting {2}",
                  "death.attack.fireworks.item": "{1} went off with a bang due to a firework fired from {3} by {2}",
                  "death.attack.badRespawnPoint.message": "{1} was killed by {2}",
                  "death.attack.badRespawnPoint.link": "Intentional Game Design",
                  "death.attack.sweetBerryBush": "{1} was poked to death by a sweet berry bush",
                  "death.attack.sweetBerryBush.player": "{1} was poked to death by a sweet berry bush whilst trying to escape {2}",
                  "death.attack.sting": "{1} was stung to death",
                  "death.attack.sting.item": "{1} was stung to death by {2} using {3}",
                  "death.attack.sting.player": "{1} was stung to death by {2}",
                  "death.attack.freeze": "{1} froze to death",
                  "death.attack.freeze.player": "{1} was frozen to death by {2}"
                  }
                  """;
    }
}
